version: '3.8'

services:
  training-job:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wms-forecast-training
    command: make train_xgboost
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1